### PR TITLE
Image and STL Upload for V3

### PR DESCRIPTION
**Pull request by eaudiffred**
Uploaded the V3 images and the V3 STL files to the V3 mechanical folder.

### CODE REVIEW

**Comment by keenanjohnson** [comment]
This all looks great to me @eaudiffred ! Will you add the updated instruction changes to this same PR?

**Comment by eaudiffred** [comment]
I have the instructions updated, but I'm not sure how to preview the page.  Is this possible for me to do before sending the pull request?

**Comment by keenanjohnson** [comment]
Awesome! There are two ways to do it:

1. It's fine to go ahead and push this to the PR and then you can preview in the web browser in the branch. That's a totally cool way, as you can just push more changes to the branch if you fix.
2. Alternatively, if you want to preview on your computer, you can do so using some text editors. I use [VSCode](https://code.visualstudio.com/) and it has a nice feature where you can right click on a .md file and preview it!

image

image

**Comment by eaudiffred** [comment]
Cool, thanks!  I'll try option #1 first.

**Comment by eaudiffred** [comment]
Ok, I think its ready to go.  Let me know what you think and if you see anything that needs fixing.

**Comment by keenanjohnson** [comment]
Thanks @eaudiffred ! I will take a look!

**Review by keenanjohnson — APPROVED** [review]
@eaudiffred this looks perfect! I'm sure there are other little tweaks and adjustments we will make as people start using this, but you've done the hardest lift here!

I'm going to merge it now! Thank you!

**Pull request merged**
