### PR TITLE
Corrected balena.yml

### PR DESCRIPTION
**Pull request by wjlove**
The correct device type for BBG Wireless is beaglebone-green-wifi.

After reviewing the balena officially supported hardware list the name for the Beaglebone Green Wireless is not beaglebone-green-wireless but rather beaglebone-green-wifi.  I apologize for the error.

### CODE REVIEW

**Comment by keenanjohnson** [comment]
Hey there @wjlove ! Thanks for the correction, but it looks like some other edits to the readme made it into this PR on accident?

**Comment by wjlove** [comment]
Oh.... I hope I didn't screw up your readme file.  I've been having problems understanding how this all works and may have included some stuff from another balena project.  Do you need me to undo something?

**Comment by keenanjohnson** [comment]
No worries at all! This is what open-source is for, a learning experience! And no worries about messing anything up. That's why we do this PRs with reviews to double check each other before pushing changes to the bigger project.

If you check out the ["Files Changed"](https://github.com/Ribbit-Network/ribbit-network-frog-sensor/pull/118/files ) section of the PR, you can see that you edited the Readme and added a new backup readme file. 

If you make a new commit undoing those changes and push it to this PR, then we should be all good.

**Review by keenanjohnson — CHANGES_REQUESTED** [review]
Please remove the README.md file changes. Thank you!

**Comment by wjlove** [comment]
So after some reading I think I did this correctly.  I've made a second commit with the readme.md.backup removed and the original readme.md restored.  Before I press any buttons, flip any switches, or turn any knobs I want to be sure I have done the correct thing(s).

**Review by keenanjohnson — APPROVED** [review]
Perfect! This looks good to me!

**Pull request merged**
