### PR TITLE
Fixing Broken Link related to issue #154

### PR DESCRIPTION
**Pull request by eaudiffred**
Broken links to international BOMs in V2 and V3.  Issue #154.  This fixes the first part of the problem stated in the issue.

### CODE REVIEW

**Comment by eaudiffred** [comment]
To correct the broken links I just routed back to the V1 folder with the V1 international BOMs.  Now that I think about it, that may not be the best idea, as it could get confusing if you are trying to build V3, but then get directed back to a V1 folder.  @keenanjohnson, let me know what you think.  Maybe it would be better to leave the link dead until we create the V3 specific international BOM.

**Comment by keenanjohnson** [comment]
Hmmmmm yeah I would hate for someone to purchase old parts because they didn't read through the description too well. perhaps we could just add a note that we have previously had international BOMs and we are looking for volunteers to localize them?

**Comment by eaudiffred** [comment]
I went ahead and added an international_boms folder to V2 and V3.  I also added a little text asking for help creating them.

**Comment by keenanjohnson** [comment]
Perfect! Thanks!

**Comment by eaudiffred** [comment]
@keenanjohnson, is there something I can do to make these reviews/approvals easier?  I know you are hyper focused on the software development right now and I don't want to add extra work to your plate!

**Review by keenanjohnson — APPROVED** [review]

**Pull request merged**
