### PR TITLE
Conformal instructions

### PR DESCRIPTION
**Pull request by eren-rudy**
Inserted optional instructions page into the assembly-instructions folder, providing guidance for where to add conformal coating to the PCBs

### CODE REVIEW

**Review by keenanjohnson — CHANGES_REQUESTED** [review]
@eren-rudy this looks really excellent! I think there are just two things we need to correct. There are two sensitive areas on the barometer and SCD30 that we need to added to the Do NOT COAT areas. I highlighted them in purple here if you can help me amend your images. These are areas where there are ports in the IC packages to allow air flow for the barometer and humidity sensor respectively. Thanks!

Screen Shot 2021-09-12 at 6 31 32 PM

**Comment by eren-rudy** [comment]
Hey @keenanjohnson, thanks for the feedback! I know you mentioned that before but I missed it. Updated my branch with the fixes.

**Review by keenanjohnson — APPROVED** [review]
Looks perfect!

**Comment by keenanjohnson** [comment]
@all-contributors please add @eren-rudy  for his great testing and documentation improvements!

**Pull request merged**
