### PR TITLE
PR to address Issue #160 and #170

### PR DESCRIPTION
**Pull request by eaudiffred**
Added in pictures and descriptions to address issues #160 and #170

### CODE REVIEW

**Comment by eaudiffred** [comment]
@keenanjohnson, is it normal for all of the commits I have made historically to appear each time I submit a new PR?  I feel like I'm doing something incorrectly here.

**Comment by keenanjohnson** [comment]
Hey @eaudiffred ! I think this is probably becase your forked copy of the repo is not being kept in sync. Super normal and a bit confusing.

If you follow these instructions, it will keep it in sync and you should only see the new commits in the PR. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

Does that make sense? Let me know any questions.

**Comment by pascaljoly** [comment]
Have the instructions been updated? it looks like they are still the old version.

**Comment by eaudiffred** [comment]
Thanks, @keenanjohnson.  I have it sync'd now.  Is there something I need to do to complete the PR after it is reviewed?

**Comment by keenanjohnson** [comment]
Hmmm @eaudiffred  I still see the other commits in this PR. Reading through the github docs, maybe you have to do the sync specifically with this PR instead of your branch? 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/keeping-your-pull-request-in-sync-with-the-base-branch

**Comment by eaudiffred** [comment]
@keenanjohnson, I'm not seeing the merge option available as shown in that instruction document.  Right now I'm seeing that merging is blocked until the changes are reviewed.  However, most of these commits you already reviewed in the last PR.  

Do you have 10 minutes sometime in the next few days to jump on a call?  I'll share my screen with you and show you how I'm making the changes each time and then submitting them.

**Comment by keenanjohnson** [comment]
Oh I think I see what has happened in this case @eaudiffred ! But also happy to jump on a call if you are still confused after this. I'll shoot you a message in Discord. It looks like in this case, you had done a merge from main to your branch a few times in the past, so that's why there are so many commits in the long. That's totally ok and I can squash those down when I merge this in shortly.

In the future, if you do the synchronize on your branch before making the changes, that will limit the number of commits in a PR. :) 

Thanks again!

**Review by keenanjohnson — APPROVED** [review]

**Pull request merged**
